---
- hosts: all
  become: yes
  vars:
    ubuntujavapackg: "openjdk-8-jre"
    redhatinstall: "java-1.8.0-openjdk"

  tasks:
    - name: Install openjdk-8 on ubuntu
      apt:
        name: "{{ubuntujavapackg}}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install openjdk-8 on redhat
      yum:
        name: "{{redhatinstall}}"
        state: present
      when: ansible_os_family == "RedHat"